@url = http://0.0.0.0:8000
@api = http://0.0.0.0:8000/api/v1

### admin
@id_admin = 09d1e435-5a1d-4f1a-9179-5077d5855069
@token_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjg2NDAwMDAwMDAwMDAwLCJpYXQiOjE3NTY1NDA0NDMsImlzcyI6ImF1dGh6IiwidXNlcklkIjoiMDlkMWU0MzUtNWExZC00ZjFhLTkxNzktNTA3N2Q1ODU1MDY5In0.TgRYFVWqwA2E7sFAJ4La-T3umOwJ8rCbxI9h9hwZLzc
### asd1
@id_user = e885181b-7c9c-437c-b790-0ca5c911cfcd
@token_user = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjg2NDAwMDAwMDAwMDAwLCJpYXQiOjE3NTY1NDAzNTEsImlzcyI6ImF1dGh6IiwidXNlcklkIjoiZTg4NTE4MWItN2M5Yy00MzdjLWI3OTAtMGNhNWM5MTFjZmNkIn0.zJUHvTTOcaV_wgmb6Ksr0WgOJgUGAZc1YWrtxniMpTY

###
GET {{url}}

###
GET {{url}}/healthz

###
POST {{api}}/auth/register

{
    "email": "minhhoccode111@gmail.com",
    "password": "Bruh0!0!"
}

###
POST {{api}}/auth/login

{
    "email": "asd0@gmail.com",
    "password": "asdasd"
}

###
GET {{api}}/users/all
    ?pageNumber=1
    &perPage=10
    &q=
    &all=true

###
GET {{api}}/auth/me
Authorization: Bearer {{token_user}}

###
GET {{api}}/users/{{id_user}}

###
PATCH {{api}}/users/{{id_user}}
Authorization: Bearer {{token_user}}

{
    "email": "asd1@gmail.com",
    "bio": "dummy"
}

###
PATCH {{api}}/users/{{id_user}}/status
Authorization: Bearer {{token_admin}}

{
    "is_active": true
}

###
PATCH {{api}}/users/{{id-user}}/password
Authorization: Bearer {{token_user}}

{
    "old_password": "Bruh0!0!",
    "new_password": "Bruh0!0!"
}

###
DELETE {{api}}/users/{{id_user}}
Authorization: Bearer {{token_admin}}
