@url = http://localhost:9999
@api = {{url}}/api/v1
@email = minhhoccode111@gmail.com
@email0 = asd0@gmail.com
@email1 = asd1@gmail.com
@password = Bruh0!0!
@username = minhhoccode111
@username0 = asd0
@username1 = asd1
@bio = i like golang
@image = https://www.w3schools.com/howto/img_avatar.png
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjAyNzEyMDgsImlhdCI6MTc1OTQwNzIwOCwiaXNzIjoiYmxvZ2FwaSIsInVzZXJJZCI6ImQ4OWIxOTQ1LTMxOTMtNDM1ZC05MGM2LWI2ZGE5NTMxNzg5MyJ9.IgV3p6itLKkUCcaJDXbTpjDtz5PY16XisJgcoAJr4gg
@token0 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjAxMDUzMTYsImlhdCI6MTc1OTI0MTMxNiwiaXNzIjoiYmxvZ2FwaSIsInVzZXJJZCI6IjdjNmVjZjlkLTBjMGQtNDNmNy05NTlmLWYzOTc3MDZhNzYwZSJ9.9D5b9AXg_K6_rv1bJEHxaSG7dIlzjmsmBUzdEfzIbr0
@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjA1MTI3NzIsImlhdCI6MTc1OTY0ODc3MiwiaXNzIjoiYmxvZ2FwaSIsInVzZXJJZCI6IjQzMGU1ZjI3LTNhYWYtNDhkNS1iOWFiLWE0ZjM2NGRkODExOSJ9.ASsV1JtaxkSrOoPlmLrErNAFo82B3Vkk3kO997drFkw
@slug = slug
@slug = title-cannot-be-empty-9
@commentId = 123

### Register
POST {{api}}/users

{
    "user": {
        "email": "{{email1}}",
        "password": "{{password}}",
        "username": "{{username1}}"
    }
}

### Login
POST {{api}}/users/login

{
    "user": {
        "email": "{{email1}}",
        "password": "{{password}}"
    }
}

### Current User
GET {{api}}/user
Authorization: Token {{token}}

### Update User
PUT {{api}}/user
Authorization: Token {{token}}

{
    "user": {
        "email": "{{email}}",
        "username": "{{username}}",
        "password": "{{password}}",
        "image": "{{image}}",
        "bio": "{{bio}}"
    }
}

### All Articles without auth
GET {{api}}/articles

### All Articles without auth, with limit and offset
GET {{api}}/articles
    ?limit=10
    &offset=10

### All Articles without auth, with limit and offset, author
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username0}}

### All Articles without auth, with limit and offset, author, favorited
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username}}
    &favorited={{username}}

### All Articles without auth, with limit and offset, author, favorited, tag
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username}}
    &favorited={{username}}
    &tag=sao

### All Articles with auth
GET {{api}}/articles
Authorization: Token {{token}}

### All Articles with auth, with limit and offset
GET {{api}}/articles
    ?limit=10
    &offset=10
Authorization: Token {{token}}

### All Articles with auth, with limit and offset, author
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username0}}
Authorization: Token {{token}}

### All Articles with auth, with limit and offset, author, favorited
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username}}
    &favorited={{username}}
Authorization: Token {{token}}

### All Articles with auth, with limit and offset, author, favorited, tag
GET {{api}}/articles
    ?limit=10
    &offset=0
    &author={{username}}
    &favorited={{username}}
    &tag=sao
Authorization: Token {{token0}}

### Create Article
POST {{api}}/articles
Authorization: Token {{token0}}

{
    "article": {
        "title": "title",
        "description": "description",
        "body": "body",
        "tagList": ["tag"]
    }
}

### Get Feed Articles
GET {{api}}/articles/feed
Authorization: Token {{token}}

### All Articles with auth
GET {{api}}/articles
Authorization: Token {{token}}

### Articles by Author with auth
GET {{api}}/articles?author={{username}}
Authorization: Token {{token}}

### Single Article by slug, without auth
GET {{api}}/articles/{{slug}}

### Single Article by slug, with auth
GET {{api}}/articles/{{slug}}
Authorization: Token {{token}}

### Update Article
PUT {{api}}/articles/{{slug}}
Authorization: Token {{token}}

{
    "article": {
        "title": "Slug",
        "body": "",
        "description": ""
    }
}

### Favorite Article
POST {{api}}/articles/slug/favorite
Authorization: Token {{token}}

### Unfavorite Article
DELETE {{api}}/articles/slug/favorite
Authorization: Token {{token}}

### Create Comment for Article
POST {{api}}/articles/{{slug}}asd/comments
Authorization: Token {{token}}

{
    "comment": {
        "body": "minhhoccode111 created a comment"
    }
}

### Get Comments for Article, without auth
GET {{api}}/articles/{{slug}}/comments
    ?limit=10
    &offset=0

### Get Comments for Article, with auth
GET {{api}}/articles/{{slug}}/comments
    ?limit=10
    &offset=0
Authorization: Token {{token}}

### All Comments for Article without login
GET {{api}}/articles/{{slug}}/comments

### Delete Comment for Article
@commentId = f342d4d6-3b20-4440-a317-1056ac8fa458
###
DELETE {{api}}/articles/{{slug}}/comments/{{commentId}}
Authorization: Token {{token}}

### Delete Article
DELETE {{api}}/articles/{{slug}}
Authorization: Token {{token}}

### Profile
GET {{api}}/profiles/{{username}}
Authorization: Token {{token}}

### Follow Profile
POST {{api}}/profiles/{{username}}/follow
Authorization: Token {{token}}

### Unfollow Profile
DELETE {{api}}/profiles/{{username}}/follow
Authorization: Token {{token0}}

### All Tags
GET {{api}}/tags
