@url = http://localhost:9999
@api = {{url}}/api/v1
@email = minhhoccode111@gmail.com
@email0 = asd0@gmail.com
@password = Bruh0!0!
@username = minhhoccode111
@username0 = asd0
@bio = i like golang
@image = https://www.w3schools.com/howto/img_avatar.png
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk5MTUxODEsImlhdCI6MTc1OTA1MTE4MSwiaXNzIjoiYmxvZ2FwaSIsInVzZXJJZCI6IjBhOWViNjNjLTZmMjYtNDlhMi1iMWFiLTc1MGNlMGNiYzYzZSJ9.iYY98NZMFCeaqBsoC1G5fJ44tE7AugYo8V6zFZ_fksM
@token0 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk5MjE5MDIsImlhdCI6MTc1OTA1NzkwMiwiaXNzIjoiYmxvZ2FwaSIsInVzZXJJZCI6IjQ4Y2UzOTAyLWIzZGItNGQxNC1iNGJkLTQyNWIzZmEyNGNmZiJ9.EwtcITJhFz_4DfkM6XhTebHn9whRkZi87rXm8KQ7na8
@slug = article-slug
@commentId = 123

### Register
POST {{api}}/users

{
    "user": {
        "email": "{{email}}",
        "password": "{{password}}",
        "username": "{{username}}"
    }
}

### Login
POST {{api}}/users/login

{
    "user": {
        "email": "{{email}}",
        "password": "{{password}}"
    }
}

### Current User
GET {{api}}/user
Authorization: Token {{token}}

### Update User
PUT {{api}}/user
Authorization: Token {{token}}

{
    "user": {
        "email": "{{email}}",
        "username": "{{username}}",
        "password": "{{password}}",
        "image": "{{image}}",
        "bio": "{{bio}}"
    }
}

### All Articles with params
GET {{api}}/articles
    ?author=johnjacob
    &favorited={{username}}
    &tag=dragons
    &limit=10
    &offset=0

### Create Article
POST {{api}}/articles
Authorization: Token {{token}}

{
    "article": {
        "title": "title cannot be empty",
        "description": "description cannot be empty",
        "body": "body cannot be empty",
        "tagList": ["tai", "vi", "sao"]
    }
}

### Feed
GET {{api}}/articles/feed
Authorization: Token {{token}}

### All Articles with auth
GET {{api}}/articles
Authorization: Token {{token}}

### Articles by Author with auth
GET {{api}}/articles?author={{username}}
Authorization: Token {{token}}

### Single Article by slug
GET {{api}}/articles/{{slug}}
Authorization: Token {{token}}

### Update Article
PUT {{api}}/articles/{{slug}}
Authorization: Token {{token}}

{
    "article": {
        "body": "With two hands"
    }
}

### Favorite Article
POST {{api}}/articles/{{slug}}/favorite
Authorization: Token {{token}}

### Articles Favorited by Username with auth
GET {{api}}/articles?favorited={{username}}
Authorization: Token {{token}}

### Unfavorite Article
DELETE {{api}}/articles/{{slug}}/favorite
Authorization: Token {{token}}

### Create Comment for Article
POST {{api}}/articles/{{slug}}/comments
Authorization: Token {{token}}

{
    "comment": {
        "body": "Thank you so much!"
    }
}

### All Comments for Article
GET {{api}}/articles/{{slug}}/comments
Authorization: Token {{token}}

### All Comments for Article without login
GET {{api}}/articles/{{slug}}/comments

### Delete Comment for Article
DELETE {{api}}/articles/{{slug}}/comments/{{commentId}}
Authorization: Token {{token}}

### Delete Article
DELETE {{api}}/articles/{{slug}}
Authorization: Token {{token}}

### Profile
GET {{api}}/profiles/{{username}}
Authorization: Token {{token}}

### Follow Profile
POST {{api}}/profiles/{{username}}/follow
Authorization: Token {{token}}

{
    "user": {
        "email": "{{email}}"
    }
}

### Unfollow Profile
DELETE {{api}}/profiles/{{username}}/follow
Authorization: Token {{token}}

### All Tags
GET {{api}}/tags
